name: Build Action

on:
  workflow_call:
    inputs:
      project-name:
        description: "Project Name (e.g. zMenu)"
        required: true
        type: string
      java-version:
        description: "Optional java version"
        required: false
        type: string
        default: "21"
      java-distribution:
        description: "Optional java distribution"
        required: false
        type: string
        default: "temurin"
      publish:
        description: "If a package should be publish through ghcr.io"
        required: false
        type: boolean
        default: false
      project-to-publish:
        description: "Name of the project to publish (e.g. API:publish)"
        required: false
        type: string
        default: "publish"
      build-command:
        description: "Optional build command to run (default to ./gradlew build)"
        required: false
        type: string
        default: "./gradlew build"
      discord-avatar-url:
        description: "Avatar url (default to zMenu avatar)"
        required: false
        type: string
        default: "https://minecraft-inventory-builder.com/storage/images/9UgcfGZyrmbVrXw5lbj5kXq6fW8F4nhwj6Cx4nVG.png"
      default-branch:
        description: "Default branch to check for releases"
        required: false
        type: string
        default: "main"
      runs-on:
        description: "Optional label for the runner to run on"
        required: false
        type: string
        default: "['ubuntu-latest']"
    secrets:
      WEBHOOK_URL:
        description: "Discord webhook url"
        required: true
      MAVEN_USERNAME:
        description: "Maven Username"
        required: true
      MAVEN_PASSWORD:
        description: "Maven password"
        required: true

jobs:
  build:
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # ratchet:actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          server-id: github
          settings-path: ${{ github.workspace }}
          cache: "gradle"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Make the short sha
        id: short_sha
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          if [ "${GITHUB_REF##*/}" = "${{ inputs.default-branch }}" ]; then
            ${{ inputs.build-command }}
          else
            ${{ inputs.build-command }} -Darchive.classifier=DEV -Dgithub.sha=${{ steps.short_sha.outputs.GITHUB_SHA_SHORT }}
          fi

      - name: Publish on maven
        if: ${{ inputs.publish && github.event_name != 'pull_request' }}
        run: |
          GRADLE_CMD="./gradlew ${{ inputs.project-to-publish }}"
          if [ "${GITHUB_REF##*/}" = "${{ inputs.default-branch }}" ]; then
            $GRADLE_CMD -Drepository.name=releases
          else
            $GRADLE_CMD -Darchive.classifier=DEV -Dgithub.sha=${{ steps.short_sha.outputs.GITHUB_SHA_SHORT }}
          fi

        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Find ${{ inputs.project-name }} JAR
        id: find_jar
        run: |
          echo "Finding ${{ inputs.project-name }} JAR..."
          jar_path=$(find target/ -name '*.jar' | head -n 1)
          echo "Found ${{ inputs.project-name }} JAR at: $jar_path"
          echo "JAR_PATH=$jar_path" >> $GITHUB_OUTPUT

      - name: Upload JAR as artifact
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4
        with:
          name: ${{ inputs.project-name }}-DEV-${{ steps.short_sha.outputs.GITHUB_SHA_SHORT }}-PR-${{ github.event.number }}-${{ github.run_id }}
          path: target/

      - name: Discord Webhook Action
        if: ${{ github.event_name != 'pull_request' }}
        uses: tsickert/discord-webhook@b217a69502f52803de774ded2b1ab7c282e99645 # ratchet:tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: "New development build of ${{ inputs.project-name }} is available!"
          avatar-url: ${{ inputs.discord-avatar-url }}
          username: ${{ inputs.project-name }}
          filename: ${{ steps.find_jar.outputs.jar_path }}
